### ISSUE TITLE
mget should use an in memory cache too

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/ft-api-client#112]

**Comment by matthew-andrews** [comment]
why?

**Comment by richard-still-ft** [comment]
The original implementation had an in-memory cache and then used mget to fetch items that had expired/were missing. So it maintained the very high performance of the memory cache and also optimised the network "cache" request by only fetching the items it needed. 

Although we use elasticSearch as a cache it isn't one. It's effectively an API that supports fetching multiple items at the same time. Functionality we hope will be in V2. You would never purge it. I think it does make sense to use an in-memory cache ultimately, it is an order of magnitude faster after all.

**Comment by commuterjoy** [comment]
I agree with @matthew-andrews here. We need fewer caching layers, not more.

**Comment by richard-still-ft** [comment]
So leave it for now, when we have better API support we can look again what the cache should look like.

**Comment by wheresrhys** [comment]
Just chatted about this. The basic reason is poor performance on /mypage. We have no/very-limited fastly caching and the page can be breakingly slow. Adding an in app cache for articles in a page which only requests the most recent articles, but in a variety of combinations, could have big performance gains.

@matthew-andrews the idea of using a cache within the request itself might not work as e.g.
user1 requests [1, 2], user2 requests [2, 3] . Then if user3 requests [1, 3] the cache won't kick in. To get the full benefit it'd need to be a per article cache, not per request.

 We only just switched to mget so will see how that improves performance and possibly revisit later

**Comment by commuterjoy** [comment]
That seems fair enough - though the core reason behind experimenting with elastic search was to make a quick/robust multi-article retrieve mechanism.

**Comment by richard-still-ft** [comment]
Indeed, how many articles are you fetching? For 10 or so you should be seeing responses in < 200ms.

**Comment by wheresrhys** [comment]
I need to revisit the graphite graphs for the api client to check, but the lack of fastly cache means that the app may end up sending many many more requests than our other apps (particularly if my page is successful and gets used by people as their first port of call, or if it starts to provide endpoints for lazy-loading 'my-content' into other pages). No matter how quick the elastic search response there's still reason to worry about the load on the app. Although more dynos = solution to every problem of that kind?
